### PR TITLE
TRITON-2272 update sdc-vmapi base image to triton-origin-x86_64-21.4.0

### PR DESCRIPTION
**Pull request by bahamat**

### CODE REVIEW

**Review by danmcd — DISMISSED** [review]
Is it possible to test this with a selective sdcadm upgrade?

**Comment by danmcd** [comment]
If this had IA, I'd check it for `master`.

**Comment by bahamat** [comment]
I've got this working on 21.4.0 now. I've installed it at home and on ducksoup. Everything seems to be working so far.

If you want to give it a try you can install the latest PR-88 image from experimental.

**Comment by danmcd** [comment]
Installed on `moe`, and seems to be okay. Anything I should test explicitly?

```
[root@moe (kebecloud) ~]# sdcadm update -C experimental vmapi 
Finding candidate update images for the "vmapi" service.
Using channel experimental

This update will make the following changes:
    download 1 image (83 MiB):
        image 1fd9c706-b556-4e2a-95c7-5050b463f7d0
            (vmapi@PR-88-20220327T174712Z-g927df4f)
    update "vmapi" service to image 1fd9c706-b556-4e2a-95c7-5050b463f7d0
        (vmapi@PR-88-20220327T174712Z-g927df4f):
        instance "bdd3c089-444a-43de-9f0f-ad92dbece8de" (vmapi0) on server 00000000-0000-0000-0000-0cc47a07f6ee

Would you like to continue? [y/N] y

Create work dir: /var/sdcadm/updates/20220327T182810Z
Downloading image a7199134-7e94-11ec-be67-db6f482136c2
    (minimal-64-lts@21.4.0)
Imported image a7199134-7e94-11ec-be67-db6f482136c2
    (minimal-64-lts@21.4.0)
Downloading image 502eeef2-8267-489f-b19c-a206906f57ef
    (triton-origin-x86_64-21.4.0@master-20220322T012137Z-g9382491)
Imported image 502eeef2-8267-489f-b19c-a206906f57ef
    (triton-origin-x86_64-21.4.0@master-20220322T012137Z-g9382491)
Downloading image 1fd9c706-b556-4e2a-95c7-5050b463f7d0
    (vmapi@PR-88-20220327T174712Z-g927df4f)
Imported image 1fd9c706-b556-4e2a-95c7-5050b463f7d0
    (vmapi@PR-88-20220327T174712Z-g927df4f)
Updating image for SAPI service "vmapi"
    service uuid: 6c830538-2c09-46ca-a295-73eb5e1c1f1b
Installing image 1fd9c706-b556-4e2a-95c7-5050b463f7d0
    (vmapi@PR-88-20220327T174712Z-g927df4f)
Reprovisioning VM bdd3c089-444a-43de-9f0f-ad92dbece8de on server 00000000-0000-0000-0000-0cc47a07f6ee
Waiting for vmapi instance bdd3c089-444a-43de-9f0f-ad92dbece8de to come up
Updated successfully (elapsed 201s).
[root@moe (kebecloud) ~]# sdc-healthcheck | grep vmapi
vmapi                                running         -                   online
[root@moe (kebecloud) ~]# svcs -xvZ
[root@moe (kebecloud) ~]# 

```

**Review by danmcd — APPROVED** [review]
Modulo any additional tests you'd like me to run, this seems okay.

**Comment by bahamat** [comment]
Anything that will exercise VMAPI. Create, destroy, resize, reprovision (needs to be done via adminui or vmapi directly), rename, start, stop.

**Comment by danmcd** [comment]
Did some deletions and one rename.  No problems (and not sure if it's psychosomatic, but it seemed faster).

**Pull request merged**
